### ISSUE TITLE
Support for dependency injection?

### ISSUE THREAD

**Issue by Hirrolot** [lunatic-solutions/submillisecond#90]
How DI is usually done in `submillisecond`? For example, I may want to pass a configuration file, a database connection, and some other stuff of my own to _some_ of my handlers. How can I do that?

**Comment by bkolobara** [comment]
Hi @Hirrolot,

lunatic's processes don't share any memory and each handler is running in a separate process. This means that the only way to share some data between two processes is to introduce a third one that holds the data. The best way to do this at the moment is to introduce a [named process](https://docs.rs/lunatic/0.11.4/lunatic/struct.Process.html#method.register) and then look it up inside each handler.

We do something similar in [the logger](https://github.com/lunatic-solutions/lunatic-log-rs), if you are looking for an example.  The `lunatic_log::init` method will spawn a process under a well defined name, and each call to `info!`, `debug!` and _others_ will look up this logging process and send it a message to log something.

**Comment by tqwewe** [comment]
@Hirrolot I've made a PR #98 which should help make using state much easier
